# Generated by Django 4.1.5 on 2023-01-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_SQLite_To_Postgres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='city_fin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='city_swe',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='name_eng',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='name_fin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='name_swe',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='operator',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
