# Generated by Django 4.1.5 on 2023-01-23 16:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_SQLite_To_Postgres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('departure_station_name', models.CharField(default='-', max_length=30)),
                ('return_station_name', models.CharField(default='-', max_length=30)),
                ('covered_distance', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(10, 'Covered distance of the journey has to be bigger than 10.')])),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10, 'Duration of the journey has to be bigger than 10s.')])),
                ('departure_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_station', to='stations.station')),
                ('return_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_station', to='stations.station')),
            ],
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['departure_time'], name='journeys_jo_departu_407bfe_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['return_time'], name='journeys_jo_return__e6e14c_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['departure_station_name'], name='journeys_jo_departu_174850_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['return_station_name'], name='journeys_jo_return__86c604_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['covered_distance'], name='journeys_jo_covered_56c865_idx'),
        ),
        migrations.AddIndex(
            model_name='journey',
            index=models.Index(fields=['duration'], name='journeys_jo_duratio_542db9_idx'),
        ),
    ]
