# Generated by Django 4.1.5 on 2023-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journeys', '0001_SQLite_To_Postgres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='departure_station_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AlterField(
            model_name='journey',
            name='return_station_name',
            field=models.CharField(default='-', max_length=50),
        ),
    ]
