# Generated by Django 4.1.5 on 2023-01-23 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvimport', '0002_CSV_file_ext_validation_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv',
            name='task_id',
            field=models.CharField(default='0', max_length=60),
        ),
    ]
